# Generated by Django 5.2.1 on 2025-06-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_badge_userbadge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='correctAnswers',
            new_name='correct_answers',
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
